Resources:
  EnquiryConsumerF2BFBD04:
    Type: AWS::S3::Bucket
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: LizYogaEnquiryConsumerLambdaStack/EnquiryConsumer/EnquiryConsumer/Resource
  EnquiryConsumerEnquiryConsumerHandlerServiceRole772EB4D9:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: LizYogaEnquiryConsumerLambdaStack/EnquiryConsumer/EnquiryConsumerHandler/ServiceRole/Resource
  EnquiryConsumerEnquiryConsumerHandlerServiceRoleDefaultPolicyE06686A2:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - s3:GetObject*
              - s3:GetBucket*
              - s3:List*
              - s3:DeleteObject*
              - s3:PutObject
              - s3:Abort*
            Effect: Allow
            Resource:
              - Fn::GetAtt:
                  - EnquiryConsumerF2BFBD04
                  - Arn
              - Fn::Join:
                  - ""
                  - - Fn::GetAtt:
                        - EnquiryConsumerF2BFBD04
                        - Arn
                    - /*
          - Action:
              - dynamodb:DescribeStream
              - dynamodb:GetRecords
              - dynamodb:GetShardIterator
              - dynamodb:ListStreams
              - dynamodb:ListShards
            Effect: Allow
            Resource: arn:aws:dynamodb:ap-southeast-2:564737888276:table/Enquiry/stream/2021-10-03T11:09:26.179
        Version: "2012-10-17"
      PolicyName: EnquiryConsumerEnquiryConsumerHandlerServiceRoleDefaultPolicyE06686A2
      Roles:
        - Ref: EnquiryConsumerEnquiryConsumerHandlerServiceRole772EB4D9
    Metadata:
      aws:cdk:path: LizYogaEnquiryConsumerLambdaStack/EnquiryConsumer/EnquiryConsumerHandler/ServiceRole/DefaultPolicy/Resource
  EnquiryConsumerEnquiryConsumerHandler0234E6E8:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParameters0c2fb1a8adbd4c10a0ce58d7db6093eb7e17c55a1512f5a8ecf059a329211b5dS3Bucket3BF9181B
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters0c2fb1a8adbd4c10a0ce58d7db6093eb7e17c55a1512f5a8ecf059a329211b5dS3VersionKey4A5647FC
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParameters0c2fb1a8adbd4c10a0ce58d7db6093eb7e17c55a1512f5a8ecf059a329211b5dS3VersionKey4A5647FC
      Role:
        Fn::GetAtt:
          - EnquiryConsumerEnquiryConsumerHandlerServiceRole772EB4D9
          - Arn
      Environment:
        Variables:
          BUCKET:
            Ref: EnquiryConsumerF2BFBD04
      Handler: EnquiryConsumerHandler.main
      Runtime: nodejs14.x
    DependsOn:
      - EnquiryConsumerEnquiryConsumerHandlerServiceRoleDefaultPolicyE06686A2
      - EnquiryConsumerEnquiryConsumerHandlerServiceRole772EB4D9
    Metadata:
      aws:cdk:path: LizYogaEnquiryConsumerLambdaStack/EnquiryConsumer/EnquiryConsumerHandler/Resource
      aws:asset:path: /home/dusan/Workspaces/github/liz-yoga-enquiry-consumer-lambda/src
      aws:asset:property: Code
  EnquiryConsumerEnquiryConsumerHandlerEnquiryTableStream575031D1:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      FunctionName:
        Ref: EnquiryConsumerEnquiryConsumerHandler0234E6E8
      BatchSize: 1
      EventSourceArn: arn:aws:dynamodb:ap-southeast-2:564737888276:table/Enquiry/stream/2021-10-03T11:09:26.179
      StartingPosition: LATEST
    Metadata:
      aws:cdk:path: LizYogaEnquiryConsumerLambdaStack/EnquiryConsumer/EnquiryConsumerHandler/EnquiryTableStream/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/2WPTY7CMAyFz8I+NTQVrAfQzA4JlROY1INC2wTFCQhFuTskRQPSrN7nHz371RBr2cBi9oU3rlTXz5V1BPHgUfViaw17F5QX21+zR4cjeXK5aIltcIoyP7c67bU1SdRy+ekVM0RuIG6C6qnYvGiSDTIlMeB47BDiTzAq++S1P/6+kvGHcmyHl4s2pzz+301C4wixtUN5qujeDlrdy/OFkuCmQmbyDOssSUxx30FL+5n+lC1TEsZ2BGeeX2sJUsJqdmatKxeM1yNBO+kDc81YzkYBAAA=
    Metadata:
      aws:cdk:path: LizYogaEnquiryConsumerLambdaStack/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Parameters:
  AssetParameters0c2fb1a8adbd4c10a0ce58d7db6093eb7e17c55a1512f5a8ecf059a329211b5dS3Bucket3BF9181B:
    Type: String
    Description: S3 bucket for asset "0c2fb1a8adbd4c10a0ce58d7db6093eb7e17c55a1512f5a8ecf059a329211b5d"
  AssetParameters0c2fb1a8adbd4c10a0ce58d7db6093eb7e17c55a1512f5a8ecf059a329211b5dS3VersionKey4A5647FC:
    Type: String
    Description: S3 key for asset version "0c2fb1a8adbd4c10a0ce58d7db6093eb7e17c55a1512f5a8ecf059a329211b5d"
  AssetParameters0c2fb1a8adbd4c10a0ce58d7db6093eb7e17c55a1512f5a8ecf059a329211b5dArtifactHashF5D858BF:
    Type: String
    Description: Artifact hash for asset "0c2fb1a8adbd4c10a0ce58d7db6093eb7e17c55a1512f5a8ecf059a329211b5d"
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - af-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2

